name: Daily Commit Bot

on:
  schedule:
    - cron: '15 9 * * *'  # Runs every day at 9:15 AM UTC
  workflow_dispatch:       # 👈 Enables manual run

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make daily commit by 24f2002227@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date)"
          git push
